//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int IdItem { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public string Category { get; set; }
        public string BonusStr { get; set; }
        public string BonusAgi { get; set; }
        public string BonusDex { get; set; }
        public string BonusVit { get; set; }
        public string BonusInt { get; set; }
        public string BonusLuk { get; set; }
        public int AccountIdAccount { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
