//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stats
    {
        public int IdStats { get; set; }
        public string Str { get; set; }
        public string Agi { get; set; }
        public string Dex { get; set; }
        public string Vit { get; set; }
        public string Int { get; set; }
        public string Luk { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
